name: small_gallery_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/basketball_1.jpeg
    - assets/images/basketball_2.jpeg
    - assets/images/bike.jpeg
    - assets/images/kaya.jpeg
    - assets/images/running.jpeg
    - assets/images/ski.jpeg
    - assets/images/soccer.jpeg
    - assets/images/tennis_1.jpeg
    - assets/images/tennis_2.jpeg